### ISSUE TITLE
Scalar (0 rank tensor) logic

### ISSUE THREAD

**Issue by adaber** [serizba/cppflow#10]
Hey, serizba

Firstly, I'd like to thank you for uploading your code that helped me understand how to use the Tensorflow C API :)

I'd also like to ask you about how your Tensor object handles scalars or 0-order tensors.

If I understand correctly, your "Tensor" constructor doesn't modify the "shape" vector in case of a scalar (n_dims == 0) and proceeds constructing the Tensor object yet you throw an exception in the "set_data" method if the vector "shape" is empty.

```
this->error_check(!this->shape.empty(), "Shape of the input Tensor is not known, please provide a shape");
```

It'd be great if you could explain the logic behind this. I assume that your code doesn't support 0-rank tensors (scalars), right ?

Thanks!

**Comment by rbgreenway** [comment]
I'm also interested in this question.  I have a network with inputs: image Tensor, scalar float, scalar bool.  How would I create the scalar inputs for the Model.run() function?

Also, the Tensor.set_data() function seems to have problems with bool data type.  Maybe because "bool" is a C++ data type, and not a C data type?



If I try to make the second 2 inputs Tensors,

**Comment by serizba** [comment]
Hi!

Sorry for answer so late. You are right, currently the code does not support scalar types. As a workaround you could declare a Tensor with a shape of (1,) or (1,1) or something like that. If you changed the code or you want to modify it feel free to open a pull request to enable scalar types.

I will also try to change the code if I have time.

Thanks
