### ISSUE TITLE
cppflow leaks memory

### ISSUE THREAD

**Issue by TensorMechanic** [serizba/cppflow#171]
Ok, I did a test and Tensorflow does release gpu memory. So, cppflow leaks somewhere.

**Comment by ljn917** [comment]
Is it possible for you to upload your full tests somewhere so that we can
fix it? Thanks.

**Comment by TensorMechanic** [comment]
meh, tensorflow is balls even my little cuda tensor is 1000x faster than it.

**Comment by TensorMechanic** [comment]
I do not think cppflow was meant to do what I am doing to it so it works fine for loading python models that behave properly. I am going back to Torch because i like it much better. Thank you.

**Comment by TensorMechanic** [comment]
To answer your question I am trying to use it like Torch but it doesn't work that way.

**Comment by TensorMechanic** [comment]
Ok I did another test this time creating massive amounts of cppflow::tensor and no leak, so in conclusion my code is retarded somewhere and has a bug. Sorry guys.

**Comment by ljn917** [comment]
FYI, are you doing something like below, i.e. calling raw_ops directly instead of loading models? For performance, I heard the eager mode was slow but never test it in C++.
<https://github.com/serizba/cppflow/blob/4be8da9d838501820cc8a7513324ca19215dab47/examples/eager_op_multithread/main.cpp#L11-L21>
