### ISSUE TITLE
Invalid GraphDef std::runtime_error

### ISSUE THREAD

**Issue by AlberBM96** [serizba/cppflow#46]
Hello!
I was trying out this tool and I bumped into an error when trying to run my own model. The example ran flawlessly.
I used Tensorflow 2.3 and Python 3.8 to create a simple sequential Keras model and train it. Then I used method "save" to export it as a Protobuf file (.pb). The C++ file is simple and based on the provided example, and it simply tries to load the model.

Is there any particular way in which Keras models should be saved in order to work with this tool?

Thanks.

**Comment by cmasteran1** [comment]
Hello, I ran into almost the exact same issue! it turns out that we need to do one extra step of preprocessing in python before we can use it here. following the example here https://github.com/opencv/opencv/issues/16879#issuecomment-603815872 seems to have fixed my issue. I believe you need to "freeze" the graph/model. be careful though,
```
f = tf.function(infer).get_concrete_function(flatten_input=tf.TensorSpec(shape=[None, 28, 28, 1], dtype=tf.float32))
```
in this line the shape is the shape of your input, and for me flatten_input was not recognized and it prompted me to fill a variable called "input_1". my input shape was [None,10] because I did not want to specify the number of points to use in the graph, however I had 10 inputs for every output. also be careful to note the dtype variable. if you chose tf.float32, then the don't initialize input and output vectors as doubles, instead initialize as floats. Finally, if your model uses more than 1 input [None, n > 1]. then you will have to reshape in cppflow when you set_data() because it doesn't know how many rows there are. hope this helps someone!

**Comment by AlberBM96** [comment]
Thanks for the help!
This actually fails when I try to implement it because my network is a quite simple Sequential with only FC layers, and apparently these type of networks do not support that.
I did some more reading on how to freeze a graph and [this post](https://stackoverflow.com/questions/60974077/how-to-save-keras-model-as-frozen-graph) partially solved my problem. Now I get an error saying _No operation named "init" exists_
