### ISSUE TITLE
Java Load DLL : infite loop

### ISSUE THREAD

**Issue by khaled-besrour** [serizba/cppflow#82]
After generating my project in a dll, I want to load it in java code to use Spring as a web service.
After researching, I found that the problems originate from the global context which is initialized by default.
I think that the load library try to load the context before finishing the load of the DLL

I corrected the problem by moving the initialisation to the function but i see a commit for the thread safe context who done the opposite.
The problem is when multiple thread try to generate the context; maybe adding a lock ?

edit : the usage of the std::call_once can be a good solution.

```cpp

static context global_context;

explicit context(TFE_ContextOptions* opts);
explicit context();

TFE_Context* context::get_context()
	{
		if(global_context.tfe_context == nullptr)
		{
			auto tf_status = context::get_status();
			std::unique_ptr<TFE_ContextOptions, decltype(&TFE_DeleteContextOptions)> opts(
				TFE_NewContextOptions(), &TFE_DeleteContextOptions);
			global_context.tfe_context = TFE_NewContext(opts.get(), tf_status);
		}
		
		return global_context.tfe_context;
	}
```

**Comment by ljn917** [comment]
We cannot declare `global_context` as `static`. TF manages thread pool and per-thread executors internally. If eager handles are created with different context, they cannot interact with each other, e.g. cannot perform operators.

On-demand construction is likely requiring a context_manager class as noted in the comments.

**Comment by khaled-besrour** [comment]
sory i use static global_context for my own project because i can't use inline which is defined in c++ 17.
I add the ` std::call_once` without change the inline what do you think about that ?

**Comment by ljn917** [comment]
As I mentioned before, I don't think it is the right way to do. A `context_manager class` is much better.

**Comment by ljn917** [comment]
In addition, your problem seems to be caused by library initialization order instead of thread safety issue.

**Comment by khaled-besrour** [comment]
Yes, the global context is a global variable which in creation create a new context, that was the problem. when loading the library it try to load context.

I want to create a `context_manager class` but i have just a question when did we need to create or delete a context.

**Comment by ljn917** [comment]
We want to keep a global context at all time, which means no deletion once created.

We also want to create the global context as early as possible to avoid the need of a mutex.

The `context_manager class` should contains a getter and a setter for the global context and avoid using lock as much as possible.

BTW, I suspect you have something like double-locking in library initialization. In addition, I strongly recommend not to declare the global context as static in the global namespace. The `static` keyword in global namespace means each translation unit creates a different copy of the variable, instead of one variable shared by all translation units. So, I guess you don't have thread safety issue at all since each thread holds their own copy of the `global_context`, but you are experiencing library initialization order issue.

**Comment by ljn917** [comment]
One common solution for per-C++17 is below.

```
// not tested
inline get_global_context() {
  static context* _gl_ctx = new context();
  return _gl_ctx;
}
```
You just call `get_global_context()` where you need the `global_context` variable. This gives you on-demand construction but slightly worse performance.

**Comment by khaled-besrour** [comment]
I want to keep the c++ 14 compatibility because i need to compile in Ubuntu 16 environment for my work (I now it's a very old distribution and are deprecated, said that to my boss :p )

**Comment by ljn917** [comment]
I know it is hard to change the production environment, unfortunately. I am compiling gcc-10 myself on the server....

**Comment by khaled-besrour** [comment]
if the problem is when creating context on dll load, i don't found a safe solution without late init  + mutex for thread safety

**Comment by ljn917** [comment]
I am not familiar with windows, but I heard that dll load is placed under a
critical section, e.g. protected by a global lock. Under that critical
section, no synchronization can be performed otherwise deadlock would occur.

The get_global_context() function should solve the problem if that's the
case.

**Comment by khaled-besrour** [comment]
I think using `std::call_once` is better after first call it performe as a goto

**Comment by ljn917** [comment]
No, it's not. Defining std::once does not prevent accidental access before
initialization. The function static variable approach uses a lock
implicitly and protect against uninitialized access.
