### ISSUE TITLE
serving_default_input_1 not being general option for all models

### ISSUE THREAD

**Issue by tranvanh** [serizba/cppflow#97]
Hi I have encountered runtime error **"No operation named "serving_default_input_1" exists"**.
After a bit of poking around, I have found out that this part of the code had to be slightly modified, specifically the serving_default string. 
`    
inline tensor model::operator()(const tensor& input) {
        return (*this)({{"serving_default_input_1", input}}, {"StatefulPartitionedCall"})[0];
    }
`
to
`    
inline tensor model::operator()(const tensor& input) {
        return (*this)({{"serving_default_lstm_input", input}}, {"StatefulPartitionedCall"})[0];
    }
`
The default serving string is not general for all types of models. In other words, it can vary depending on the model architecture. The correct serving_default string can be acquired by listing model operations and reading the output above "StatefulPartitionedCall". Not sure whether this was already mentioned in docs or examples or not. If yes, I must have overlooked it.

**Comment by serizba** [comment]
Hi @tranvanh 
Thanks for your message. Yes we know that only certain models work with `serving_default_input`, that's why we also provide a complex calling operator, where you can specify the signature that you need. You don't need to change the code, just use the other operator. See the [docs](https://serizba.github.io/cppflow/quickstart.html#complex-model-call-multi-input-output-models).

**Comment by tranvanh** [comment]
Ah yes, apparently I did overlook it 😄. Thanks! I'm closing the issue then.

**Comment by bmiftah** [comment]
I am having this same probem  No operation named "serving_default_input_1" exists when calling/infering my tensorflow model . I roam around to fix this probem and I was lead here. Assuming cppflow model.h  expect such naming , I even try to change my model's input name to serving_default_input_1 like this : **inputs = Input((IMG_HEIGHT, IMG_WIDTH, 1), name="serving_default_input_1"**)  so that I can pass this probem . But it keep coming whatever I do. I saw @tranvanh seems to have a work around but I didnt quite get it from the above explanation . Did you change that part of Cppflow or you adjuest your input tensorf name ?  My other model with savedmodel format can load and work prefectly. But the one failing to run is saved with a different criteria, i.e  I just loaded trained weight on the clean un-trained model so that It can be loaded faster ... But I throws bug.  here is the outpu tlog I got when I load and make prediction on my segmation mode : 2023-03-10 **20:06:49.461410: I tensorflow/cc/saved_model/reader.cc:45] Reading SavedModel from: Saved_skeleton_Model
2023-03-10 20:06:49.502748: I tensorflow/cc/saved_model/reader.cc:89] Reading meta graph with tags { serve }
2023-03-10 20:06:49.503183: I tensorflow/cc/saved_model/reader.cc:130] Reading SavedModel debug info (if present) from: Saved_skeleton_Model
2023-03-10 20:06:49.607709: I tensorflow/compiler/mlir/mlir_graph_optimization_pass.cc:357] MLIR V1 optimization pass is not enabled
2023-03-10 20:06:49.639549: I tensorflow/cc/saved_model/loader.cc:229] Restoring SavedModel bundle.
2023-03-10 20:06:50.276635: I tensorflow/cc/saved_model/loader.cc:213] Running initialization op on SavedModel bundle at path: Saved_skeleton_Model
2023-03-10 20:06:50.483632: I tensorflow/cc/saved_model/loader.cc:305] SavedModel load for tags { serve }; Status: success: OK. Took 1022231 microseconds.
terminate called after throwing an instance of 'std::runtime_error'
  what():  No operation named "serving_default_input_1" exists
Aborted (core dumped)**
I have been into this for nearly a month and I appreciate any help on resolvinf issue or even how to make loading the model faster ... Thannk you and pardon me for length question.  Looking forward helpful tip !

**Comment by tranvanh** [comment]
Hi :}

after training your model, use `trainedModel.input` in python, you will get something like 
```
<KerasTensor: shape=(None, 60, 31) dtype=float64 (created by layer 'bidirectional_2_input')>
```
in this case `bidirectional_2_input` is what you're looking for. Basically then in `mode.h` change the serving in
```
inline tensor model::operator()(const tensor& input) {
  return (*this)({{"serving_default_input_1", input}},
                 {"StatefulPartitionedCall"})[0];
}
```
 to `serving_bidirectional_2_input`.
 
 Hope that makes sense. If anything don't hesitate and ask away :}

**Comment by bmiftah** [comment]
Thank you so much for your repy.  Based on your suggestion , I was able to  obtain the input tensor of  my  model using input_tensor = model_loaded.input   and here is what I got :  

 _KerasTensor(type_spec=TensorSpec(shape=(None, 224, 224, 1), dtype=tf.float32, name='serving_default_input_1'), name='serving_default_input_1', description="created by layer 'serving_default_input_1'")_

According to  your suggestion ,  **serving_default_input_1** ,  is the one I should pick up from the above output.  In my case this happen to be the same as the one in cpplof ,  model.h   . Here is how that line in model.h  looks like 
_inline tensor model::operator()(const tensor& input) {                                                                                                                   
  
   _return (*this)({{"serving_default_input_1", input}},                                                                                                                    
                  {"StatefulPartitionedCall"})[0];                                                                                                                         
}_   

and it seems I shouldn't make change to that line.  But the error still contine to appear when I run my model with : 

cppflow::model model("saved_model.pb",cppflow::model::TYPE::FROZEN_GRAPH);    note that the my model IS FROZEN model !
  
  I notice that in your case , it was **bidirectional_2_input**  and you changed to serving_default_input_1 in the corrosponding name in model.h.  - it worked for you , right ?

I guess the reason why my input tensor name is 'serving_default_input_1'  is because I changed my model's input tenosor to 'serving_default_input_1' when I first face this '**_No operation named serving_default_input_1 found_** ' error  so that cppflow will not throw the error "No operation named "serving_default_input_1"    , But I stumbled into this same error even after changing  ... a little bewildering .   
Here is the one thing I am suscpious about the reason: - since your output tensor is 'bidirectional_2_input'  and you changed the one in model.h by adding the string 'serving' and got , serving_bidirectional_2_input, and following this trend , I may need to add the string 'serving' to 'serving_default_input_1' and make it 'serving_serving_default_input_1' ... this is the last thing I am think about the reason , it may look wired ...  Can you think of any reason for this problem ? 

when I run saved_model_cli show --dir SavedModel09 --tag_set serve --signature_def serving_default     on the original model , 

here is what I got ,  

The given SavedModel SignatureDef contains the following input(s):
  inputs['input_1'] tensor_info:
      dtype: DT_FLOAT
      shape: (-1, 224, 224, 1)
      name: serving_default_input_1:0
The given SavedModel SignatureDef contains the following output(s):
  outputs['conv2d_45'] tensor_info:
      dtype: DT_FLOAT
      shape: (-1, 224, 224, 1)
      name: StatefulPartitionedCall:0
Method name is: tensorflow/serving/predict

...
... 

I wonder if this can give additional tips to solve the problem .  My Model is **Frozen** one !! 

  It spins my head and I thank you so much once again for your kind help !

**Comment by tranvanh** [comment]
It might be related in someway with your type being frozen graph. I did a bit of digging whether frozens get their inputs in different manner. I stumbled across this: [Save, Load and Inference From TensorFlow 2.x Frozen Graph](https://leimao.github.io/blog/Save-Load-Inference-From-TF2-Frozen-Graph/). Overall I would try to search for **tensorflow frozen graph input** if that could shed some light on the issue. Just some thoughts on top of my head, I have no experience with these :/ But personally I would try to explore overall inputs of of frozen graphs :}

**Comment by bmiftah** [comment]
Yes.  You are right. Thank you for sharing that link. I mange to explore my fozen graph and explore the original graph from which I did the freezing. From the list of long output( list of nodes for the frzonen graph) , I was able to see these two interesting output : 
**Tensor("args_0:0", shape=(None, 224, 224, 1), dtype=float32)
Tensor("Identity:0", shape=(None, 224, 224, 1), dtype=float32)**

I then go to the location where cppflow model.h expects the defaut input and output , and replace them with the above output , namely **args_0** and **Idenity** , and guess what ? It worked.  But I still want to understand how these two names came about. It looks tensorflow internally gave these names.  This is despite the fact that I give explicit name for my input and output layer in my model. As you point out,   the reason could be the way how frozen graph get their names . some default names are flying around until we rename them. I will ty look into it further.  I thank you for your help.
